[ ohmyzsh ]
tags = [ "terminal" ]

[ ohmyzsh_plugins ]
tags = [ "terminal" ]
options = []

[ p10k ]
tags = [ "terminal" ]

[ vimrc ]
tags = [ "terminal" ]

[ brew ]
tags = [ "pkg-man" ]

[ brew_packages ]
tags = [ "packages" ]
options = [
  "jq",
  "kubectl"
]

[ brew_cask_packages ]
tags = [ "packages" ]

[ anaconda ]
tags = [ "python" ]

[ nvm ]
tags = [ "nodejs" ]

[ node_lts ]
tags = [ "nodejs" ]

[ node_version ]
tags = []
options = []

[ sdkman ]
tags = [ "java" ]

[ git_clone ]
tags = []
options = []
