[ change_to_zsh ]
tags = [ "terminal" ]

[ ohmyzsh ]
tags = [ "terminal" ]

[ ohmyzsh_plugins ]
tags = [ "terminal" ]
options = [
  "https://github.com/zsh-users/zsh-autosuggestions",
  "https://github.com/zsh-users/zsh-syntax-highlighting"
]

[ p10k ]
tags = [ "terminal" ]

[ vimrc ]
tags = [ "terminal" ]

[ brew ]
tags = [ "pkg-man" ]

[ brew_packages ]
tags = [ "packages" ]
options = [
  "neofetch",
  "jq",
  "kubectl",
  "mysql",
  "rocksdb",
  "sbt"
]

[ brew_cask_packages ]
tags = [ "packages" ]
options = [
  "visual-studio-code",
  "pycharm-ce",
  "intellij-idea-ce",
  "docker",
  "zoom",
  "slack"
]

[ anaconda ]
tags = [ "python" ]

[ nvm ]
tags = [ "nodejs" ]

[ node_lts ]
tags = [ "nodejs" ]

[ node_version ]
tags = []
options = []

[ sdkman ]
tags = [ "java" ]

[ git_clone ]
tags = []
options = []

[ "deb_package+vscode" ]
tags = [ "vscode" ]
options = [
  "'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'"
]

[ vscode_extensions ]
tags = [ "editors" ]
options = [
  "akamud.vscode-theme-onedark",
  "EditorConfig.EditorConfig",
  "mohsen1.prettify-json",
  "ms-azuretools.vscode-docker",
  "ms-vscode-remote.remote-containers",
  "redhat.vscode-yaml"
]

[ "vscode_extensions+python" ]
tags = [ "python" ]
options = [
  "ms-python.python",
  "ms-python.vscode-pylance",
  "ms-toolsai.jupyter",
  "ms-toolsai.jupyter-keymap",
  "ms-toolsai.jupyter-renderers",
  "ms-vscode-remote.remote-containers"
]

[ "vscode_extensions+scala" ]
tags = [ "scala" ]
options = [
  "scala-lang.scala"
]

[ apt_get_packages ]
tags = []
options = [
  "--no-install-recommends",
  "git",
  "zsh",
  "neofetch",
  "vim",
  "curl"
]

[ "deb_package+chrome" ]
tags = [ "chrome" ]
options = [
  "'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'"
]

[ "deb_package+slack" ]
tags = [ "slack" ]
options = [
  "'https://downloads.slack-edge.com/releases/linux/4.27.156/prod/x64/slack-desktop-4.27.156-amd64.deb'"
]

[ jetbrains_toolbox ]
tags = [ "jetbrains" ]
options = []

[ "snap_package+kubectl" ]
tags = [ "kubectl", "kubernetes", "k8s" ]
options = [
  "kubectl",
  "--classic"
]

[ "snap_package+helm" ]
tags = [ "helm", "kubernetes", "k8s" ]
options = [
  "helm",
  "--classic"
]
