# [ main ]
# title = "Nathaniel's Computer Setup"
# tags = [ 
#   "all", 
#   "java",
#   "nodejs",
#   "pkg-man", 
#   "python", 
#   "terminal",
# ]
# os = [ "macos", "linux" ]

# [ git ]
# config = false
# # repos = [
# #   ""
# # ]

[ ohmyzsh ]
tags = [ "terminal" ]
# run_zsh = true
# # plugins = [
# #   ""
# # ]

[ p10k ]
tags = [ "terminal" ]

[ vimrc ]
tags = [ "terminal" ]

[ brew ]
tags = [ "pkg-man" ]

[ anaconda ]
tags = [ "python" ]

[ nvm ]
tags = [ "nodejs" ]

[ node ]
tags = [ "nodejs" ]
# lts = true
# # versions = [ 16 ]

[ sdkman ]
tags = [ "java" ]
