# this file contains all names of things that you can install and the references to the appropriate shell function in functions.sh
ohmyzsh = "install_ohmyzsh"
ohmyzsh_plugins = "install_ohmyzsh_plugins"

p10k.macos = "prettify_terminal"
p10k.linux = "prettify_terminal_linux"

vimrc = "install_vimrc"

brew = "install_brew"
brew_packages = "brew_install"
brew_cask_packages = "brew_install_cask"

anaconda.macos = "install_anaconda3"
anaconda.linux = "install_anaconda3_linux"

nvm = "install_nvm"
node_lts = "install_node_lts"
node_version = "install_node"

sdkman = "install_sdkman"

atom_packages = "install_atom_packages"
vscode_extensions = "install_vscode_extensions"

git_config = "create_git_config"
git_clone = "git_clone_repo"

apt_get_packages.linux = "apt_get_install"

deb_package.linux = "install_deb_package"

jetbrains_toolbox.linux = "install_jetbrains_toolbox"

snap_package.linux = "install_snap_package"
