# this file contains all names of things that you can install and the references to the appropriate shell function in functions.sh
[ ohmyzsh ]
install_function = "install_ohmyzsh"

[ zsh_successful_cmd_filter ]
install_function = "install_zsh_successful_cmd_filter"

[ install_ohmyzsh_plugins ]
install_function = "install_ohmyzsh_plugins"

[ add_ohmyzsh_plugins ]
macos.install_function = "add_ohmyzsh_plugins_macos"
linux.install_function = "add_ohmyzsh_plugins_linux"

[ p10k ]
macos.install_function = "prettify_terminal"
linux.install_function = "prettify_terminal_linux"

[ vimrc ]
install_function = "install_vimrc"

[ brew ]
install_function = "install_brew"

[ brew_packages ]
install_function = "brew_install"

[ brew_cask_packages ]
install_function = "brew_install_cask"

[ anaconda ]
macos.install_function = "install_anaconda3"
linux.install_function = "install_anaconda3_linux"

[ nvm ]
install_function = "install_nvm"

[ node_lts ]
install_function = "install_node_lts"

[ node_version ]
install_function = "install_node"

[ sdkman ]
install_function = "install_sdkman"

[ sdk_candidate ]
install_function = "install_sdk_candidate"

[ atom_packages ]
install_function = "install_atom_packages"

[ vscode_extensions ]
install_function = "install_vscode_extensions"

[ git_config ]
install_function = "create_git_config"

[ git_clone ]
install_function = "git_clone_repo"

[ apt_get_packages ]
linux.install_function = "apt_get_install"
linux.sudo = true

[ deb_package ]
linux.install_function = "install_deb_package"
linux.sudo = true

[ jetbrains_toolbox ]
linux.install_function = "install_jetbrains_toolbox"

[ snap_package ]
linux.install_function = "install_snap_package"
linux.sudo = true

[ docker ]
linux.install_function = "install_docker"
linux.sudo = true
