name: "alfa"
description: A cli tool to kickstart your dev environment and set you up to soar!
repository: "https://github.com/nyoungstudios/setup"
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  toml: "^0.12.0"